id: outside_accent_lights
alias: "Outside Accent Lights"
description: >-
  Turn on the exterior outside lights 30 minutes before sunset, and turn them off again 30 minutes after sunrise.

triggers:
- alias: "30m Before Sunset"
  trigger: sun
  event: sunset
  offset: "-00:30:00"
- alias: "30m After Sunrise"
  trigger: sun
  event: sunrise
  offset: "00:30:00"
- alias: "Home Assistant (Re)Started"
  trigger: homeassistant
  event: start

actions:
- choose:
  - conditions:
    - condition: sun
      after: sunset
      before: sunrise
      after_offset: "-00:30:00"
      before_offset: "00:30:00"
    sequence:
    - alias: 'Turn On Lights'
      action: light.turn_on
      data:
        entity_id: light.outdoor_accent_lights

  - conditions:
    - condition: sun
      after: sunrise
      before: sunset
      after_offset: "00:30:00"
      before_offset: "-00:30:00"
    sequence:
    - alias: 'turn Off Lights'
      action: light.turn_off
      data:
        entity_id: light.outdoor_accent_lights
