id: outside_accent_lights_off

alias: "Turn Off Outside Accent Lights after Sunrise"

triggers:
- id: on_startup
  alias: "On Startup"
  platform: homeassistant
  event: start
- id: sunrise
  alias: "30m After Sunrise"
  trigger: sun
  event: sunrise
  offset: "00:30:00"

conditions:
- alias: 'Between 30m after sunrise and 30m before sunset'
  condition: sun
  after: sunrise
  after_offset: "00:30:00"
  before: sunset
  before_offset: "-00:30:00"

actions:
- alias: 'Turn Off Selected Lights'
  action: script.light_or_switch_turn_off
  data:
    entity_id: >-
        {{-
          expand('group.outdoor_accent_lights')
          | map(attribute='entity_id')
          | list
        -}}
