id: outside_accent_lights_on

alias: "Turn On Outside Accent Lights before Sunset"

triggers:
- id: on_startup
  alias: "On Startup"
  platform: homeassistant
  event: start
- id: sunset
  alias: "30m Before Sunset"
  trigger: sun
  event: sunset
  offset: "-00:30:00"

conditions:
- alias: 'Between 30m before sunset until 30m after sunrise'
  condition: sun
  after: sunset
  after_offset: "-00:30:00"
  before: sunrise
  before_offset: "00:30:00"

actions:
- alias: 'Turn On Selected Lights'
  action: script.light_or_switch_turn_on
  data:
    entity_id: >- 
        {{-
          expand('group.outdoor_accent_lights')
          | map(attribute='entity_id')
          | list
        -}}
