default_config:
prometheus: !include prometheus.yaml

homeassistant: !include homeassistant.yaml
frontend: !include frontend.yaml

automation: !include ../automations.yaml
# automation code: !include_dir_list automations/

input_boolean: !include_dir_merge_named inputs/boolean/
input_number: !include_dir_merge_named inputs/number/

light: !include_dir_merge_list lights/
cover: !include_dir_merge_list covers/

notify: !include_dir_list notify/

scene: !include ../scenes.yaml
scene code: !include_dir_list scenes/

script: !include ../scripts.yaml
script code: !include_dir_named scripts/

template: !include_dir_merge_list template_entities/

timer: !include_dir_merge_named timers/

# HACS integration configs
yahoofinance: !include hacs-configs/yahoofinance.yaml
