default_config:
http: !include http.yaml
prometheus: !include prometheus.yaml

homeassistant: !include homeassistant.yaml

automation: !include automations.yaml
automation code: !include_dir_list automations/

light: !include_dir_merge_list lights/

scene: !include scenes.yaml
scene code: !include_dir_list scenes/
