default_config:
homeassistant: !include homeassistant.yaml

http: !include http.yaml

automation: !include automations.yaml
automation code: !include_dir_list automations/

light: !include_dir_merge_list lights/

prometheus: !include prometheus.yaml
