id: garage_interior_lights_on
alias: "Turn On Garage Interior Lights"

triggers:
- alias: "The Foyer Door opens"
  trigger: state
  entity_id: binary_sensor.qolsys_iq4_alarm_panel_foyer_door
  to: "on"
- alias: "The Garage Service Door opens"
  trigger: state
  entity_id: binary_sensor.qolsys_iq4_alarm_panel_garage_man_door
  to: "on"
- alias: "The Garage Interia camera detects a person"
  trigger: state
  entity_id: binary_sensor.garage_interior_person_detected
  from: "off"
  to: "on"
- alias: "The Garage Door Opens"
  trigger: state
  entity_id: cover.ratgdo32_disco_door
  to:
  - open
  - opening

conditions:
- or:
  - alias: "The Garage Door is currently closed"
    condition: state
    entity_id: cover.ratgdo32_disco_door
    state: closed
  - alias: "It is Night Time"
    condition: sun
    after: sunset
    after_offset: "-00:30:00"
    before: sunrise
    before_offset: "00:30:00"

actions:
- alias: "Turn On the Garage Interior Lights"
  action: light.turn_on
  entity_id: light.garage_lights
