id: living_room_tv_off_fireplace_off
alias: "Living Room TV Off: Fireplace Off"
description: >-
  Turn off the Fireplace if it is on and the TV turns off

triggers:
- alias: "When the Living Room TV Turns Off"
  trigger: state
  entity_id: media_player.living_room_stream_box
  not_from:
  - "unavailable"
  - "unknown"
  to: "off"

conditions:
- alias: "The Living Room Fireplace is On"
  condition: state
  entity_id: light.living_room_fireplace
  state: "on"

actions:
- action: light.turn_off
  target:
    entity_id: light.living_room_fireplace
