id: living_room_tv_mood_lights
alias: "Evening Living Room TV Mood Lighting"
description: >-
  Configure lights for some nice mood lighting if the TV is turned on in the evening.

triggers:
- id: sunset
  alias: "30m Before Sunset"
  trigger: sun
  event: sunset
  offset: "-00:30:00"
- id: tv_on
  alias: "When the Living Room TV Turns On"
  trigger: state
  entity_id:
  - media_player.living_room_stream_box
  to: "on"

conditions:
- alias: "30m before Sunset until Sunrise"
  condition: sun
  after: sunset
  after_offset: "-00:30:00"
  before: sunrise
- alias: "The Living Room TV Is On"
  condition: state
  entity_id: media_player.living_room_stream_box
  state: "on"

actions:
- action: scene.turn_on
  target:
    entity_id: scene.night_tv
  data:
    transition: 5.0
