id: master_bedroom_zen34
alias: "Master Bedroom ZEN34 Remote"

variables:
  scene_key_up: '001'
  scene_key_down: '002'

triggers:
- id: zjs_scene_trigger
  alias: "Z-Wave Scene Change Event"
  platform: event
  event_type: zwave_js_value_notification
  event_data:
    # Listen for all scene change KeyPressed events for this node, the action section will check specific scene and
    # press counts from the trigger event data.
    node_id: 257
    property: scene

actions:
- alias: 'Determine Button'
  choose:
  - alias: 'Up Paddle'
    conditions:
    - condition: template
      value_template: '{{ trigger.event.data.property_key == scene_key_up }}'
    sequence:
    - choose:
      - alias: "Pressed Once"
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
        - action: light.turn_on
          target:
            entity_id: light.master_bedroom_ceiling_fan

      - alias: 'Pressed Twice'
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
        - parallel:
          - action: fan.turn_on
            data:
              percentage: 66
            target:
              entity_id: fan.master_bedroom_ceiling_fan
          - action: fan.turn_on
            data:
              percentage: 66
            target:
              entity_id: fan.master_bedroom_pedestal_fan

      - alias: 'Pressed Three Times'
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.value == "KeyPressed3x" }}'
        sequence:
        - parallel:
          - action: light.turn_on
            target:
              entity_id: light.office_ceiling_fan
          - action: fan.turn_on
            data:
              percentage: 66
            target:
              entity_id: fan.office_ceiling_fan

  - alias: 'Down Paddle'
    conditions:
    - condition: template
      value_template: '{{ trigger.event.data.property_key == scene_key_down }}'
    sequence:
    - choose:
      - alias: "Pressed Once"
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.value_raw == "KeyPressed" }}'
        sequence:
        - action: light.turn_off
          target:
            entity_id: light.master_bedroom_ceiling_fan

      - alias: 'Pressed Twice'
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.value_raw == "KeyPressed2x" }}'
        sequence:
        - parallel:
          - action: fan.turn_off
            target:
              entity_id: fan.master_bedroom_ceiling_fan
          - action: fan.turn_off
            target:
              entity_id: fan.master_bedroom_pedestal_fan

