name: CI
on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Check Config
        run: make

      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
