id: master_bathroom_off
alias: "Master Bathroom Off"
description: >-
  Turn off all Master Bathroom related entities when the lights turn off.

mode: restart

triggers:
- id: lights_off
  alias: "Bathroom Lights turned off"
  trigger: state
  entity_id: light.master_bathroom_lights
  from: "on"
  to: "off"
- id: shower_lights_off
  alias: "Shower Lights turned off"
  trigger: state
  entity_id: light.master_bathroom_shower_lights
  from: "on"
  to: "off"

actions:
- alias: "Turn off all related lights"
  parallel:
  - action: light.turn_off
    target:
      entity_id:
      - light.master_bathroom_lights
      - light.master_bathroom_shower_lights
      - light.master_bathroom_toilet_light
    data:
      transition: 2
  - action: switch.turn_off
    target:
      entity_id: switch.master_closet_light

- if:
  - alias: "The shower was running within the last 20 minutes"
    condition: and
    conditions:
    - alias: "The shower is currently off"
      condition: state
      entity_id: switch.u_by_moen_037d8f
      state: "off"
    - alias: "The shower transitioned to 'off' less than 20m ago"
      condition: template
      value_template: "{{ states.switch.u_by_moen_037d8f.last_changed < now() - timedelta(minutes=20) }}"
  - alias: "The bathroom fan is still on"
    condition: state
    entity_id: switch.master_bathroom_fan
    state: "on"
  
  then:
  - alias: "Wait until the shower has been off for 20m"
    delay: "{{ (timedelta(minutes=20) - (now() - states.switch.u_by_moen_037d8f.last_changed)).total_seconds() | int }}"
  - alias: "Turn off the fan"
    action: switch.turn_off
    target:
      entity_id: switch.master_bathroom_fan
