id: master_bathroom_shade_via_switch
alias: "Master Bathroom Shade Control"
description: >-
  Control the window shade in the master bathroom with the dimmer for the bathroom lights. Pressing the up button three
  times opens the shade, and the down button three times closes it.

variables:
  scene_key_up: '001'
  scene_key_down: '002'

triggers:
- id: light_button_press_3x
  alias: "Light Switch Button Pressed 3x"
  platform: event
  event_type: zwave_js_value_notification
  event_data:
    node_id: 15
    property: scene
    value: KeyPressed3x

actions:
- alias: 'Determine Button'
  choose:
  - alias: 'Up Paddle'
    conditions:
    - condition: template
      value_template: '{{ trigger.event.data.property_key == scene_key_up }}'
    sequence:
    - action: cover.set_cover_position
      target:
        entity_id: cover.master_bathroom_shade
      data:
        position: 65
  - alias: 'Down Paddle'
    conditions:
    - condition: template
      value_template: '{{ trigger.event.data.property_key == scene_key_down }}'
    sequence:
    - alias: "Close the Shade"
      action: cover.set_cover_position
      target:
        entity_id: cover.master_bathroom_shade
      data:
        position: 0
