id: master_bathroom_shower_prep
alias: "Master Bathroom Shower Prep"
description: >-
  Setup the Master Bathroom for a Shower when the shower is turned on or the up button on the bathroom fan switch is
  pressed twice.

variables:
  scene_key_up: &scene_key_up '001'

triggers:
- id: fan_switch_up_button_2x
  alias: "Fan Up Button Pressed 2x"
  platform: event
  event_type: zwave_js_value_notification
  event_data:
    node_id: 19
    property: scene
    property_key: *scene_key_up
    value: KeyPressed2x
- id: shower_turned_on
  alias: "The Shower was turned on"
  trigger: state
  entity_id: switch.u_by_moen_037d8f
  from: "off"
  to: "on"

actions:
- alias: "Activate Shower Prep Scene"
  action: scene.turn_on
  target:
    entity_id: scene.master_bathroom_start_shower
  data:
    transition: 2.0
